### ISSUE TITLE
unclear output/instructions

### ISSUE THREAD

**Issue by tcurdt** [pcboy/g81_relative#2]
When it says -14 deg does that mean "turn CCW 14 deg" to reach the correct position? or does that mean it's off by that and I need to turn CW?

**Comment by tcurdt** [comment]
Of course one can work it out through the raw values but being a bit more explicit would be nice.

**Comment by pcboy** [comment]
I agree that it could be misinterpreted. -14deg is supposed to be a direct translation from the raw values. So it's more like "You are currently -14deg from the correct position so you have to turn CW 14 deg.".

Any idea how we could make that more clear in the output? What if we add to all the positive values a CCW suffix and absolute the negative ones and append a CW?  
Something this:

```
      Degrees:
      -50°	-14°	-7°
      -58°	0	36°
      -65°	14°	14°

```
Becomes this:

```
      Degrees:
      50°CW	14°CW	7°CW
      58°CW	0	36°CCW
      65°CW	14°CCW	14°CCW

```

I thought we could also directly use unicode arrows for that.
```
      Degrees:
      50°↷	14°↷	7°↷
      58°↷	0	36°↶
      65°↷	14°↶	14°↶
```

Would that be clearer?

**Comment by tcurdt** [comment]
Thanks for the clarification. My first instinct was "-14deg is meant to be CCW". No wonder I was almost tearing my hairs out ;)

While the unicode arrows would be nice I find them a little small.
CW/CCW is a pretty standard denotation. I'd vote for that.
But either works.

Thanks for the nice little script!

**Comment by pcboy** [comment]
Just added the CW/CCW to the output. Should be reflected soon to the web UI after deployment.  
Thanks for the suggestion. :)
