### ISSUE TITLE
Incorrect screw direction with certain inputs

### ISSUE THREAD

**Issue by wivb0** [pcboy/g81_relative#5]
Example:
Recv:   0.10750  0.18454  0.18565  0.11083  -0.03991  -0.26657  -0.56917
Recv:   0.16639  0.19696  0.17156  0.09019  -0.04717  -0.24050  -0.48981
Recv:   0.20333  0.19786  0.14950  0.05824  -0.07591  -0.25294  -0.47287
Recv:   0.21833  0.18722  0.11944  0.01500  -0.12611  -0.30389  -0.51833
Recv:   0.21139  0.16505  0.08141  -0.03954  -0.19779  -0.39334  -0.62620
Recv:   0.18250  0.13135  0.03539  -0.10537  -0.29094  -0.52131  -0.79648
Recv:   0.13167  0.08611  -0.01861  -0.18250  -0.40556  -0.68778  -1.02917

Here, the right side is too low. But the output says to screw it in lower:
      Degrees:
      65°CW	72°CW	396°CW
      144°CW	0	360°CW
      86°CW	122°CW	727°CW

      Fractional Turns:
      1/5CW	1/5CW	11/10CW
      2/5CW	0	1/1CW
      1/5CW	3/10CW	2/1CW
    
Expect: right side should be counter-clockwise

**Comment by pcboy** [comment]
Hi,

Many thanks for the catch. There was actually an issue in the parsing of the negative numbers. I pushed a fix that should be deployed to the web UI soon.
